"use client"
import { Social } from "@/types";
import Image from "next/image";
import Link from "next/link";
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xxMEcZDP1Cj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { useEffect, useState } from "react";
import { SocialIcon } from "react-social-icons";

export const dynamic = 'force-dynamic';

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
// export const dynamic = 'force-dynamic';

interface SocialsProps{
  data: Social[]
}


export const Socials : React.FC<SocialsProps>= ({
  data
}) => {
  const [isMounted, setIsMounted] = useState(false); 
  useEffect(()=>{
    setIsMounted(true)
  }, [])
  if(!isMounted){
    return null
  }

  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-muted" id="socials">
      <Link href="#socials"></Link>
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">You can find me on</h2>
          <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Follow me on your favorite platforms to stay up-to-date with my latest updates and projects.
          </p>
        </div>
        <div className="flex flex-wrap gap-5 items-center justify-center">
          {data.map((social) => (
            <Link
              key = {social.id}
              href={social.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex flex-col items-center gap-2 hover:text-primary transition-colors"
            >
              <div className="bg-background p-3 rounded-full">
                <Image
                  src={social.icon}
                  alt={social.title}
                  width={30}
                  height={30}
                  />
              </div>
              <span className="text-sm font-medium">{social.title}</span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  )
}